# Generated by Django 6.0.4 on 2026-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=120)),
                ('surgery_type', models.CharField(max_length=120)),
                ('target_duration_days', models.PositiveIntegerField()),
                ('overview', models.TextField()),
                ('weekly_objectives', models.JSONField(default=list)),
                ('self_check_prompts', models.JSONField(default=list)),
                ('care_team_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['specialty', 'title'],
            },
        ),
    ]
