# Generated by Django 6.0.4 on 2026-04-25 17:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('audience', models.CharField(max_length=120)),
                ('cadence', models.CharField(max_length=80)),
                ('intro_text', models.TextField()),
                ('medically_validated_by', models.CharField(max_length=160)),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=50)),
                ('scheduled_for', models.DateField(default=datetime.date.today)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('escalated', 'Escalated')], default='submitted', max_length=20)),
                ('answers', models.JSONField(default=dict)),
                ('pain_score', models.PositiveSmallIntegerField(default=0)),
                ('free_text', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.questionnairetemplate')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
