# Generated by Django 6.0.4 on 2026-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_code', models.CharField(max_length=50)),
                ('pain_level', models.PositiveSmallIntegerField()),
                ('has_fever', models.BooleanField(default=False)),
                ('bleeding_level', models.CharField(max_length=20)),
                ('swelling_level', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('computed_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('triggered_rules', models.JSONField(default=list)),
                ('care_recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('trigger_conditions', models.JSONField(default=list)),
                ('immediate_action', models.TextField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
