# Generated by Django 6.0.4 on 2026-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('phase', models.CharField(max_length=120)),
                ('difficulty', models.CharField(max_length=80)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('equipment', models.JSONField(default=list)),
                ('instructions', models.JSONField(default=list)),
                ('validation_criteria', models.JSONField(default=list)),
                ('media_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['phase', 'title'],
            },
        ),
    ]
